# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Data Visualization Course
tagline:             ''
description:         ''
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Erik Wiffin
  email:             erik.wiffin@gmail.com

# Custom vars
version:             1.0.0
